# Generated by Django 4.0.2 on 2022-02-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_shortlistcandidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlistcandidate',
            name='is_shortlist',
            field=models.BooleanField(default=0),
        ),
    ]
