# Generated by Django 4.0.2 on 2022-02-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_alter_shortlistcandidate_is_shortlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='is_shortlist',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'Reject'), ('3', 'Selected')], default='1', max_length=3),
        ),
    ]
