# Generated by Django 4.0.2 on 2022-02-28 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userAccounts', '0003_alter_hrprofile_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='no user', max_length=255)),
                ('email', models.EmailField(default='abc@gmail.com', max_length=255)),
                ('contactNumber', models.CharField(max_length=10)),
                ('degree', models.CharField(choices=[('0', 'B.Tech'), ('1', 'M.Tech'), ('2', 'MCA'), ('3', 'BCA'), ('4', 'B.Sc'), ('5', 'M.Sc')], default='0', max_length=6)),
                ('college', models.CharField(max_length=255)),
                ('experience', models.CharField(choices=[('0', 'FRESHER'), ('1', '1'), ('2', '2'), ('3', '3+'), ('4', '5+')], default='0', max_length=6)),
                ('skills', models.CharField(max_length=255)),
                ('ResumeLink', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
